#!/bin/bash
echo -n " Enterpath name to insert hello to that file or directory"
read file

LINE_TO_ADD="You have been hacked hahahahahahah"

check_if_line_exists()
{
    # grep wont care if one or both files dont exist.
    grep -qsFx "$LINE_TO_ADD" $file

}

add_line_to_profile()
{
    profile=$file

    [ -w "$profile" ] || profile=$file 

    printf "%s\n" "$LINE_TO_ADD" >> "$profile"
}

check_if_line_exists || add_line_to_profile
